#!/usr/bin/env python3
"""One page of CUDA results, assembled from the result files under results/cuda*/.

    python scripts/cuda_summary.py

Reads only committed result files (each records the script, commit and device that produced
it) and writes results/cuda/summary.md: exactness at scale and decoding speed on the RTX PRO
6000, prompt speed, and the models that run on a smaller GPU where BF16 does not load.
"""

import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
RES = REPO / "results"
MODELS = [
    ("Llama-3.1-8B-Instruct", "Llama 3.1 8B"),
    ("Qwen3.5-9B", "Qwen3.5 9B"),
    ("gemma-4-12B-it", "Gemma 4 12B"),
    ("gemma-4-26B-A4B-it", "Gemma 4 26B-A4B (MoE)"),
    ("gemma-4-31B-it", "Gemma 4 31B"),
]
SMALL = [("cuda-l4", "gemma-4-12B-it", "Gemma 4 12B", "NVIDIA L4"), ("cuda-a100", "gemma-4-26B-A4B-it", "Gemma 4 26B-A4B (MoE)", "NVIDIA A100 40 GB")]


def j(p: Path):
    return json.loads(p.read_text()) if p.exists() else None


def pct(x: float) -> str:
    return f"{100 * x:.1f}%"


def main():
    lines = [
        "# Binade on NVIDIA GPUs",
        "",
        "Generated by `scripts/cuda_summary.py` from the result files linked in each row. MLX 0.32.2 with its CUDA backend.",
        "Binade's matrix-vector kernels mirror MLX's own CUDA kernel (one warp per row, the same reduction), so outputs are bit-identical to BF16;",
        "multi-row products rebuild BF16 weights for cuBLAS, exact by construction. 8-bit is MLX's affine quantization (group 64), shown for reference: smaller and faster, but its outputs change.",
        "",
        "## Exactness at scale (NVIDIA RTX PRO 6000 Blackwell, 96 GB)",
        "",
        "32 windows of 512 WikiText-2 tokens (logits at all 16,352 positions) and 32 greedy generations of 128 tokens, against the resident BF16 model.",
        "",
        "| model | Binade: identical logits | Binade: identical generations | 8-bit: identical logits | 8-bit: argmax agreement | 8-bit: identical generations |",
        "|---|---|---|---|---|---|",
    ]
    for m, name in MODELS:
        e = j(RES / "cuda" / m / "exactness_scale.json")
        if not e:
            continue
        b, q = e["variants"]["binade"], e["variants"].get("q8")
        lines.append(
            f"| [{name}](../cuda/{m}/exactness_scale.md) | {b['positions_bit_identical']:,} / {b['positions']:,} | {b['generations_identical']} / {b['generations']} | "
            + (f"{q['positions_bit_identical']:,} / {q['positions']:,} | {pct(q['argmax_agreement'])} | {q['generations_identical']} / {q['generations']} |" if q else "| | |")
        )
    lines += [
        "",
        "## Decoding speed and memory (RTX PRO 6000)",
        "",
        "Greedy decoding at batch 1, median of 3 fresh processes; peak GPU memory of the decoding process.",
        "",
        "| model | BF16 tok/s | Binade tok/s | Binade / BF16 | 8-bit tok/s | peak GB: BF16 / Binade / 8-bit |",
        "|---|---|---|---|---|---|",
    ]
    for m, name in MODELS:
        d = j(RES / "cuda" / m / "decode_speed.json")
        if not d:
            continue
        med, runs = d["median_tok_s"], d["runs"]
        peak = {k: max(r["peak_gb"] for r in v) for k, v in runs.items()}
        lines.append(
            f"| [{name}](../cuda/{m}/decode_speed.md) | {med['bf16']:.1f} | {med['binade_r4']:.1f} | {med['binade_r4'] / med['bf16']:.2f}x | "
            + (f"{med['q8']:.1f}" if "q8" in med else "")
            + f" | {peak['bf16']:.1f} / {peak['binade_r4']:.1f}" + (f" / {peak['q8']:.1f}" if "q8" in peak else "") + " |"
        )
    lines += [
        "",
        "## Time to the first token (RTX PRO 6000)",
        "",
        "Prompt of WikiText-2 text filled into the KV cache as mlx_lm's generate_step does, then the last token's logits; median of 3. Binade rebuilds BF16 weights for cuBLAS, so prompts cost more than with BF16.",
        "",
        "| model | 40 tokens: BF16 / Binade / 8-bit (s) | 2048 tokens: BF16 / Binade / 8-bit (s) |",
        "|---|---|---|",
    ]
    for m, name in MODELS:
        p = j(RES / "cuda" / m / "prompt_speed.json")
        if not p:
            continue
        s = p["median_s"]
        cell = lambda L: " / ".join(f"{s[k][L]:.3f}" for k in ("bf16", "binade_r4", "q8") if k in s)
        lines.append(f"| [{name}](../cuda/{m}/prompt_speed.md) | {cell('40')} | {cell('2048')} |")
    lines += [
        "",
        "## Where BF16 does not fit",
        "",
        "On a GPU too small for the BF16 checkpoint, BF16 fails to load (out of GPU memory) while Binade runs, with outputs checked against BF16 decoder layers streamed from disk.",
        "",
        "| GPU | model (BF16 weights) | BF16 | Binade: peak GB, decode tok/s | Binade against BF16 | 8-bit: peak GB, decode tok/s |",
        "|---|---|---|---|---|---|",
    ]
    bf16_gb = {"gemma-4-12B-it": 23.92, "gemma-4-26B-A4B-it": 51.61}  # checkpoint sizes, results/*/roundtrip_v2.md
    for d, m, name, gpu in SMALL:
        base = RES / d / m
        f = j(base / "fit_probe.json")
        if not f:
            continue
        v = {r["variant"]: r for r in f["variants"]}
        dec = j(base / "decode_speed.json")
        g = j(base / "generate_check_r4_v2_streamed_binade_first.json")
        e = j(base / "exactness_scale.json")
        checks = []
        if e:
            b = e["variants"]["binade"]
            checks.append(f"{b['positions_bit_identical']:,} / {b['positions']:,} positions identical")
        if g:
            checks.append("prompt logits and 64 tokens identical" if g["identical_logits"] and g["identical_ids"] else "generation check FAILED")
        tok = lambda k: dec["median_tok_s"][k] if dec and k in dec["median_tok_s"] else v[k].get("tok_s")
        bf = v.get("bf16", {})
        lines.append(
            f"| [{gpu} ({f['device_memory_gb']:.1f} GB)](../{d}/{m}/fit_probe.md) | {name} ({bf16_gb[m]:.1f} GB) | {'runs' if bf.get('ok') else 'does not load (out of memory)'} | "
            f"{v['binade_r4']['peak_gb']:.1f} GB, {tok('binade_r4'):.1f} tok/s | {'; '.join(checks)} | "
            + (f"{v['q8']['peak_gb']:.1f} GB, {tok('q8'):.1f} tok/s |" if v.get("q8", {}).get("ok") else "|")
        )
    out = RES / "cuda" / "summary.md"
    out.write_text("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
